name: Deploy Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 */5 * * *'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py spotipy Flask gunicorn
        pip install pynacl
        pip install pytube

    - name: Run Discord Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        python bot.py & search.py
        sleep 10  # Wait for bot to start
        ps aux | grep python  # Check if the bot process is running
