name: Deploy Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 */5 * * *'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py spotipy Flask gunicorn
        pip install pynacl

    - name: Print environment variables
      run: |
        echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}"
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}"

    - name: Run Flask with Gunicorn
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      run: |
        nohup gunicorn -w 4 -b 0.0.0.0:8888 bot:app --access-logfile gunicorn_access.log --error-logfile gunicorn_error.log &
        sleep 10  # Wait for Gunicorn to start

    - name: Check running processes
      run: |
        ps aux | grep gunicorn
        ps aux | grep python

    - name: Run Discord Bot
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        nohup python bot.py &
        sleep 10  # Wait for bot to start
        ps aux | grep python  # Check if the bot process is running
