name: Deploy Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 */5 * * *'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py spotipy Flask gunicorn

    - name: Run bot
      env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        nohup gunicorn -w 4 -b 0.0.0.0:8888 bot:app &
        nohup python bot.py &
